"""CAD file exporter: STL, OBJ, simplified STEP, G-code (CNC, 3D print, laser).

Also generates QC reports and procurement specification dicts.
"""

from __future__ import annotations

import logging
import math
import os
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

import numpy as np
import trimesh

from ..models.manufacturing import (
    CNCParams,
    LaserParams,
    PrintParams,
    ValidationResult,
)

logger = logging.getLogger(__name__)


class CADExporter:
    """Export meshes to various formats and generate reports."""

    @staticmethod
    def _validate_filepath(filepath: str) -> str:
        """Resolve and validate filepath to prevent path traversal attacks."""
        resolved = os.path.realpath(os.path.abspath(filepath))
        # Must be an absolute path with no null bytes
        if "\x00" in filepath:
            raise ValueError("Filepath contains null bytes")
        # Reject paths with suspicious traversal patterns before resolution
        if re.search(r"\.\.[/\\]", filepath):
            raise ValueError(f"Path traversal detected in filepath: {filepath}")
        return resolved

    @staticmethod
    def export_stl(mesh: trimesh.Trimesh, filepath: str, binary: bool = True) -> str:
        """Export mesh to STL file. Returns filepath."""
        filepath = CADExporter._validate_filepath(filepath)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        if binary:
            data = mesh.export(file_type="stl")
        else:
            data = mesh.export(file_type="stl_ascii")
        with open(filepath, "wb") as f:
            f.write(data)
        logger.info("Exported STL -> %s (%d bytes)", filepath, len(data))
        return filepath

    @staticmethod
    def export_obj(mesh: trimesh.Trimesh, filepath: str) -> str:
        """Export mesh to Wavefront OBJ. Returns filepath."""
        filepath = CADExporter._validate_filepath(filepath)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        data = mesh.export(file_type="obj")
        with open(filepath, "wb") as f:
            f.write(data)
        return filepath

    @staticmethod
    def export_step(mesh: trimesh.Trimesh, filepath: str) -> str:
        """Export a simplified STEP-like ASCII representation.

        Note: Full STEP (ISO 10303) requires a dedicated kernel (e.g. OpenCASCADE).
        This produces a human-readable approximation useful for documentation.
        """
        filepath = CADExporter._validate_filepath(filepath)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
        bounds = mesh.bounds if mesh.bounds is not None else np.zeros((2, 3))
        lines = [
            "ISO-10303-21;",
            "HEADER;",
            f"FILE_DESCRIPTION(('Text-to-CAD Export'),'2;1');",
            f"FILE_NAME('{os.path.basename(filepath)}','{now}',('Text-to-CAD'),(''),",
            "  'Text-to-CAD v1.0','','');",
            "FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));",
            "ENDSEC;",
            "DATA;",
            f"/* Bounding box: min={bounds[0].tolist()} max={bounds[1].tolist()} */",
            f"/* Vertices: {len(mesh.vertices)}  Faces: {len(mesh.faces)} */",
            f"/* Volume: {float(mesh.volume):.4f} mm3  Area: {float(mesh.area):.4f} mm2 */",
        ]
        for i, v in enumerate(mesh.vertices):
            lines.append(f"#V{i+1}=CARTESIAN_POINT('',(%.6f,%.6f,%.6f));" % tuple(v))
        for i, f in enumerate(mesh.faces):
            lines.append(f"#F{i+1}=FACE_BOUND('',({f[0]+1},{f[1]+1},{f[2]+1}),.T.);")
        lines += ["ENDSEC;", "END-ISO-10303-21;"]
        with open(filepath, "w") as fh:
            fh.write("\n".join(lines))
        return filepath

    # ------------------------------------------------------------------ #
    # G-code exports                                                       #
    # ------------------------------------------------------------------ #

    @staticmethod
    def export_gcode_cnc(
        mesh: trimesh.Trimesh,
        filepath: str,
        params: Optional[CNCParams] = None,
    ) -> str:
        """Generate simplified 3-axis CNC G-code."""
        if params is None:
            params = CNCParams()
        filepath = CADExporter._validate_filepath(filepath)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        bounds = mesh.bounds if mesh.bounds is not None else np.zeros((2, 3))
        min_b, max_b = bounds[0], bounds[1]
        size = max_b - min_b
        lines = [
            f"; CNC G-code generated by Text-to-CAD",
            f"; Material: {params.material}",
            f"; Tool diameter: {params.tool_diameter}mm",
            f"; Spindle: {params.spindle_speed} RPM  Feed: {params.feed_rate} mm/min",
            f"; Bounding box: X[{min_b[0]:.3f},{max_b[0]:.3f}] Y[{min_b[1]:.3f},{max_b[1]:.3f}] Z[{min_b[2]:.3f},{max_b[2]:.3f}]",
            "G21         ; metric units",
            "G90         ; absolute positioning",
            "G17         ; XY plane",
            f"S{params.spindle_speed} M3  ; spindle on",
            "G0 Z5       ; rapid to safe height",
            "G0 X0 Y0    ; rapid to origin",
            "",
            "; ----- Facing pass -----",
        ]
        # Simple facing pass
        step = params.tool_diameter * 0.8
        y = min_b[1]
        z_top = max_b[2] + params.stock_allowance
        lines.append(f"G0 Z{z_top:.3f}")
        lines.append(f"G1 Z{max_b[2]:.3f} F{params.feed_rate * 0.5:.0f}")
        while y <= max_b[1] + step:
            lines.append(f"G1 X{max_b[0]:.3f} Y{y:.3f} F{params.feed_rate:.0f}")
            y += step
            lines.append(f"G1 X{min_b[0]:.3f} Y{y:.3f}")
            y += step
        lines += [
            "",
            "; ----- Contouring pass -----",
            f"G0 Z{z_top:.3f}",
            f"G1 Z{min_b[2]:.3f} F{params.feed_rate * 0.3:.0f}",
            f"G1 X{min_b[0]:.3f} Y{min_b[1]:.3f} F{params.feed_rate:.0f}",
            f"G1 X{max_b[0]:.3f} Y{min_b[1]:.3f}",
            f"G1 X{max_b[0]:.3f} Y{max_b[1]:.3f}",
            f"G1 X{min_b[0]:.3f} Y{max_b[1]:.3f}",
            f"G1 X{min_b[0]:.3f} Y{min_b[1]:.3f}",
            "G0 Z10      ; retract",
            "M5          ; spindle off",
            "M30         ; program end",
        ]
        with open(filepath, "w") as fh:
            fh.write("\n".join(lines))
        return filepath

    @staticmethod
    def export_gcode_3dprint(
        mesh: trimesh.Trimesh,
        filepath: str,
        params: Optional[PrintParams] = None,
    ) -> str:
        """Generate simplified FDM 3D-printing G-code (RepRap/Marlin compatible)."""
        if params is None:
            params = PrintParams()
        filepath = CADExporter._validate_filepath(filepath)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        bounds = mesh.bounds if mesh.bounds is not None else np.zeros((2, 3))
        min_b, max_b = bounds[0], bounds[1]
        height = max_b[2] - min_b[2]
        num_layers = max(1, int(math.ceil(height / params.layer_height)))
        lines = [
            f"; 3D Print G-code generated by Text-to-CAD",
            f"; Printer: {params.printer_type}  Material: {params.material}",
            f"; Layer height: {params.layer_height}mm  Infill: {params.infill_percent}%",
            f"; Layers: {num_layers}",
            "M104 S{nozzle} ; set nozzle temp".format(nozzle=int(params.nozzle_temperature)),
            "M140 S{bed}    ; set bed temp".format(bed=int(params.bed_temperature)),
            "M109 S{nozzle} ; wait nozzle".format(nozzle=int(params.nozzle_temperature)),
            "M190 S{bed}    ; wait bed".format(bed=int(params.bed_temperature)),
            "G28             ; home all",
            "G21             ; metric",
            "G90             ; absolute",
            "M82             ; absolute extruder",
            "G1 Z0.3 F5000  ; raise nozzle",
        ]
        e = 0.0
        for layer in range(num_layers):
            z = min_b[2] + (layer + 0.5) * params.layer_height
            lines.append(f"\n; Layer {layer + 1}/{num_layers}  Z={z:.3f}")
            lines.append(f"G0 Z{z:.3f} F5000")
            # Simple perimeter trace
            cx = (min_b[0] + max_b[0]) / 2
            cy = (min_b[1] + max_b[1]) / 2
            rx = (max_b[0] - min_b[0]) / 2
            ry = (max_b[1] - min_b[1]) / 2
            perimeter = 2 * (rx * 2 + ry * 2)
            e += perimeter * params.layer_height * params.nozzle_diameter / (math.pi * 0.875)
            lines.append(f"G1 X{min_b[0]:.2f} Y{min_b[1]:.2f} F{params.print_speed * 60:.0f}")
            lines.append(f"G1 X{max_b[0]:.2f} Y{min_b[1]:.2f} E{e:.4f}")
            lines.append(f"G1 X{max_b[0]:.2f} Y{max_b[1]:.2f} E{e + perimeter * 0.25:.4f}")
            e += perimeter * 0.5
            lines.append(f"G1 X{min_b[0]:.2f} Y{max_b[1]:.2f} E{e:.4f}")
            lines.append(f"G1 X{min_b[0]:.2f} Y{min_b[1]:.2f} E{e + perimeter * 0.25:.4f}")
            e += perimeter * 0.25
        lines += [
            "\n; End of print",
            "M104 S0  ; nozzle off",
            "M140 S0  ; bed off",
            "M84      ; motors off",
        ]
        with open(filepath, "w") as fh:
            fh.write("\n".join(lines))
        return filepath

    @staticmethod
    def export_gcode_laser(
        profile: List[List[float]],
        filepath: str,
        params: Optional[LaserParams] = None,
    ) -> str:
        """Generate laser cutting G-code for a 2-D profile (list of [x,y] points)."""
        if params is None:
            params = LaserParams()
        filepath = CADExporter._validate_filepath(filepath)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        speed_mm_min = params.speed * 60
        lines = [
            f"; Laser cut G-code generated by Text-to-CAD",
            f"; Material: {params.material}  Thickness: {params.sheet_thickness}mm",
            f"; Power: {params.power}%  Speed: {params.speed}mm/s  Kerf: {params.kerf_width}mm",
            "G21          ; metric",
            "G90          ; absolute",
            "G0 X0 Y0     ; home",
            f"M3 S0        ; laser armed (off)",
        ]
        for _pass in range(params.passes):
            lines.append(f"\n; Pass {_pass + 1}/{params.passes}")
            if profile:
                sx, sy = profile[0]
                lines.append(f"G0 X{sx:.3f} Y{sy:.3f}   ; move to start")
                lines.append(f"M3 S{int(params.power * 10)}  ; laser on")
                for px, py in profile[1:]:
                    lines.append(f"G1 X{px:.3f} Y{py:.3f} F{speed_mm_min:.0f}")
                lines.append(f"G1 X{sx:.3f} Y{sy:.3f} F{speed_mm_min:.0f}  ; close path")
                lines.append("M5 S0        ; laser off")
        lines += ["G0 X0 Y0     ; return home", "M2           ; program end"]
        with open(filepath, "w") as fh:
            fh.write("\n".join(lines))
        return filepath

    # ------------------------------------------------------------------ #
    # Reports                                                              #
    # ------------------------------------------------------------------ #

    @staticmethod
    def generate_qc_report(
        mesh: trimesh.Trimesh,
        validation_result: ValidationResult,
    ) -> Dict[str, Any]:
        """Generate a quality control report dict."""
        bounds = mesh.bounds if mesh.bounds is not None else np.zeros((2, 3))
        size = (bounds[1] - bounds[0]).tolist() if mesh.bounds is not None else [0, 0, 0]
        return {
            "report_type": "QC",
            "generated_at": datetime.utcnow().isoformat(),
            "mesh_stats": {
                "vertex_count": len(mesh.vertices),
                "face_count": len(mesh.faces),
                "volume_mm3": float(mesh.volume) if mesh.is_volume else None,
                "surface_area_mm2": float(mesh.area),
                "bounding_box_mm": {
                    "x": round(size[0], 3),
                    "y": round(size[1], 3),
                    "z": round(size[2], 3),
                },
                "is_watertight": mesh.is_watertight,
                "is_manifold": mesh.is_volume,
            },
            "validation": {
                "is_valid": validation_result.is_valid,
                "error_count": validation_result.error_count(),
                "warning_count": validation_result.warning_count(),
                "issues": [i.dict() for i in validation_result.issues],
            },
            "pass_fail": "PASS" if validation_result.is_valid else "FAIL",
        }

    @staticmethod
    def generate_procurement_specs(
        validation_result: ValidationResult,
        materials: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Return a procurement specification with McMaster-Carr and DigiKey part numbers."""
        if materials is None:
            materials = ["aluminum_6061"]
        specs: Dict[str, Any] = {
            "generated_at": datetime.utcnow().isoformat(),
            "materials": [],
            "fasteners": [],
            "tooling": [],
        }
        # Material catalogue (representative McMaster part numbers)
        material_catalog: Dict[str, Dict] = {
            "aluminum_6061": {
                "name": "Aluminum 6061-T6",
                "mcmaster_part": "9246K14",
                "form": "Rod stock / Sheet",
                "spec": "ASTM B221",
                "note": "General purpose structural aluminum",
            },
            "steel_1018": {
                "name": "Low Carbon Steel 1018",
                "mcmaster_part": "1388K12",
                "form": "Round rod",
                "spec": "ASTM A108",
                "note": "Machinable mild steel",
            },
            "pla": {
                "name": "PLA Filament 1.75mm",
                "mcmaster_part": "N/A",
                "digikey_part": "1528-2554-ND",
                "form": "1 kg spool",
                "spec": "ISO/ASTM 52900",
                "note": "FDM 3D printing",
            },
            "acrylic_3mm": {
                "name": "Acrylic Sheet 3mm",
                "mcmaster_part": "8505K754",
                "form": "Sheet 12x24 in",
                "spec": "ASTM D4802",
                "note": "Laser cutting",
            },
        }
        for mat in materials:
            info = material_catalog.get(mat, {
                "name": mat,
                "mcmaster_part": "See supplier",
                "form": "As required",
                "spec": "See datasheet",
                "note": "",
            })
            specs["materials"].append(info)
        # Standard fasteners
        specs["fasteners"] = [
            {"type": "M3 Socket Head Cap Screw 10mm", "mcmaster_part": "92290A112", "qty": 4},
            {"type": "M5 Hex Nut", "mcmaster_part": "90592A095", "qty": 4},
        ]
        # Tooling
        specs["tooling"] = [
            {"type": "6mm 4-Flute End Mill", "mcmaster_part": "8878A24", "note": "CNC"},
            {"type": "3mm Drill Bit", "mcmaster_part": "2912A27", "note": "CNC drilling"},
        ]
        return specs
